**Question 1**

In [23]:
x = [1, 2, 3]
y = 'bootcamp'
z = x + y

TypeError: can only concatenate list (not "str") to list

x is a list, while y is a string. We cannot add a string to a list through the addition (+) function. For z to run without error, both x and y need to be strings or both need to be lists.

**Question 2**

The function that gives their type is ***type***( ), while the function that gives us the number of elements they contain is ***len***( ).

In [25]:
type(x), len(x)

(list, 3)

In [26]:
type(y), len(y)

(str, 8)

**Question 3**

In [27]:
type(2)
#2 is an integer

int

In [28]:
type('2')
#'2' is a string because 2 it is contained in quotation marks

str

In [29]:
type(2.0)
#2.0 is a float because it has decimal points

float

In [30]:
type("2.0")
#"2.0" is a string because 2.0 is contained in quotation marks

str

In [31]:
type(2>1)
#2>1 is a boolean value because it is a variable that is either true or false

bool

In [1]:
type('Itamar'>'Chase')
#This is a boolean value because it is a variable that is either true or false

bool

In [2]:
type([1, 2])
#[1, 2] is a list containing 2 elements, 1 and 2

list

In [4]:
type((1, 2))
#(1, 2) is a tuple, as signified by the round brackets.

tuple

In [5]:
type({1: "one", 2: "two"})
#This is a dictionary, with the values 1 and 2 being keys
#"one" and "two" are the values assigned to 1 and 2, respectively

dict

**Question 4**

In [104]:
print("The value of " + "1>=0 " + "is " +str(1>=0))
print("The value of " + "1 >= 1 " + "is " +str(1>=1))
print("The value of " + "1 > 1 " + "is " +str(1>1))
print("The value of " + "1==1 " + "is " +str(1==1))
print("The value of " + "1 == 1.0 " + "is " +str(1==1.0))
print("The value of " + """'Spencer' == "Spencer" """ + "is " +str('Spencer'=="Spencer"))
print("The value of " + "2**3 > 3**2 " + "is " +str(2**3 > 3**2))
print("The value of " + "1 >= 0 or 1 <= 2 " + "is " +str(1 >= 0 or 1 <= 2))
print("The value of " + "1 >= 0 and 1 <= 2 " + "is " +str(1 >= 0 and 1 <= 2))

The value of 1>=0 is True
The value of 1 >= 1 is True
The value of 1 > 1 is False
The value of 1==1 is True
The value of 1 == 1.0 is True
The value of 'Spencer' == "Spencer" is True
The value of 2**3 > 3**2 is False
The value of 1 >= 0 or 1 <= 2 is True
The value of 1 >= 0 and 1 <= 2 is True


The values above are all Boolean values.

**Question 5**

In [14]:
if 2>1
    print('Yes, 2 is still greater than 1')

SyntaxError: invalid syntax (<ipython-input-14-07a70d6c9420>, line 1)

The error here stems from the lack of a colon (:) after "if 2>1"

In [15]:
if 2>1:
    print('Yes, 2 is still greater than 1')

Yes, 2 is still greater than 1


**Question 6**

In [20]:
if True:
    print("on the one hand")
else:
    print("but on the other hand")

on the one hand


Conditional statements are written in the form of *"if condition is true, then execute the (code in the following line)"*.

Writing a condition results in a boolean value, which is either *True* or *False*. Here, by writing *True*, we basically skip the step where the code determines the Boolean value (whether the statement is *True* or *False*) and we instead just give the conditional statement the Boolean value of *True*.

Thus, **"on the one hand"** is printed because that is the result specified when the conditional statement is *True*.

In [22]:
if False:
    print("on the one hand")
else:
    print("but on the other hand")

but on the other hand


Unlike the previous case, the conditional statement will not print **"on the one hand"** because the Boolean value is *False*, thus it executes the line of code associated with "else".

The code after "else" is executed if none of the previous conditions are satisfied, i.e. when all the previous Boolean values are *False*. Here, the Boolean value is indeed *False*, thus **"but on the other hand"** is printed.

In [21]:
if not True:
    print("on the one hand")
else:
    print("but on the other hand")

but on the other hand


Similar to the previous case, the Boolean value is not *True*, i.e. it is *False*. Thus, the line of code associated with "else" is executed. The code will thus print **"but on the other hand"**.

**Question 7**

In [23]:
cond = True
if cond:
    x = "Chase"
else:
    x = "Dave"
print(x)

Chase


Similar to question 6, we directly give a Boolean value to the conditional statement (instead of writing a condition which the code will convert to a Boolean value of either *True* or *False*).

Thus, as we give the conditional statement the Boolean value, *True*, the conditional statement will execute **"x = "Chase"** because we have specified this to be the executable code when the condition is fulfilled (when the Boolean value is *True*).

**Question 8**

In [24]:
x = [1, 2, 3, 4]
y = ['x', 'y', 'z']

In [25]:
if len(x)>len(y):
    print('x has more')
else:
    print("y has at least as many")

x has more


**Question 9**

**Slicing** is an operation that can be done on *strings* and *lists*. We can take out specific parts of a *string* or *list* by specifying the location of the part (by specifying the location as an integer in a square bracket after the *string* or *list*). In the case of a *string*, we take out individual characters from the *string* when we **slice** it. For *lists*, we take out individual elements within the *list* when we **slice** it.

It is also important to note that Python starts numbering from zero, thus what we would consider the first item in a *list* or the first character in a *string* is represented by the number 0.

In [27]:
#example of slicing a string
"string"[2]
#this will "slice" the character "r" from the string, as "r" is character number 2 (in Python)

'r'

In [28]:
#example of slicing a list
test_list = ["item number 0", "item number 1", "item number 2", "item number 3"]
test_list[1]

'item number 1'

**Question 10**

In [30]:
x = [1, 2, 3, 4, 5]

first_element = x[0]
#this takes the first element in x

last_element = x[-1]
#this takes the last element in x(-1 is the last element)

all_but_last = x[0:-1]
#this takes element 0 until but not including -1, i.e. it takes the first element until
#but not including the last element

print(first_element)
print(last_element)
print(all_but_last)

1
5
[1, 2, 3, 4]


**Question 11**

In [35]:
sentence = "This is a sentence; please slice it"
#there are 35 characters in this string, thus the characters are numbered 0-34

print(sentence[0:4])
print(sentence[5:7])
print(sentence[8:9])
print(sentence[10:18])
print(sentence[20:26])
print(sentence[27:32])
print(sentence[33:])
#leaving the part after the colon empty means we slice everything after (and including) the
#character specified before the colon

This
is
a
sentence
please
slice
it


**Question 12**

In [37]:
x = [1, 2, "a", 'b', "fast", 'slow', 3, "Raghu", 'Liuren', 10]
first_item = x[0] #this slices the first item
last_item = x[-1] #this slices the last item
b_to_3_inclusive = x[3:7] #this slices item number 3 ('b') to item number 6 (3)

print(first_item)
print(last_item)
print(b_to_3_inclusive)

1
10
['b', 'fast', 'slow', 3]


**Question 13**

In [38]:
x = [1, 2, "a", 'b', "fast", 'slow', 3, "Raghu", 'Liuren', 10]
for item in x:
    print(item)

1
2
a
b
fast
slow
3
Raghu
Liuren
10


**Question 14**

In [39]:
x = [1, 2, "a", 'b', "fast", 'slow', 3, "Raghu", 'Liuren', 10]
for item in x:
    if type(item) == str:
        print(item)

a
b
fast
slow
Raghu
Liuren


**Question 15**

In [40]:
range?

**range(3,12,2)** will create a sequence of integers starting from 3 and stopping at but not including 12, where there is an increase of 2 from one integer to the subsequent integer.

In [43]:
list(range(3,12,2))

[3, 5, 7, 9, 11]

**Question 16**

In [71]:
sum = 0

thirty = list(range(0,31))
for item in thirty:
    if int(str(round(item/3,1))[-1]) == 0:
        #we only consider values whose first decimal point is 0
        sum = sum + item

        
print(sum)

165


In [72]:
#this is just a proof that the values that are chosen under the given condition are the
#correct values (i.e. multiples of 3)

thirty = list(range(0,31))
for item in thirty:
    if int(str(round(item/3,1))[-1]) == 0:
        print(item)

0
3
6
9
12
15
18
21
24
27
30


**Question 17**

In [84]:
def pocket_change(penny, nickel, dime, quarter):
    total = round(penny/100 + nickel*5/100 + dime*10/100 + quarter*25/100,2)
    return total

In [85]:
pocket_change(1,2,3,4)

1.41

In [86]:
def pocket_change_challenging(penny, nickel, dime, quarter):
    total = round(penny/100 + nickel*5/100 + dime*10/100 + quarter*25/100,2)
    return "The total is $"+str(total)

In [87]:
pocket_change_challenging(1,2,3,4)

'The total is $1.41'

**Question 18**

In [88]:
def notsix(the_list):
    shortlist = []
    for item in the_list:
        if str(item)[0] != "6":
            shortlist.append(item)
    print(shortlist)

In [89]:
qn18_list = [1234, 6783, 6, 4321, 9876]
notsix(qn18_list)

[1234, 4321, 9876]


**Question 19**

In [90]:
old_list = [1234, 6783, 6, 4321, 9876]
new_list = [x for x in old_list if str(x)[0] != "6"]

**old_list = [1234, 6783, 6, 4321, 9876]** creates a list named **old_list** containing the values within the square brackets.



**new_list** creates a new list containing elements from **old_list** that satisfy a specified condition. The specified condition is that the first digit of the element is not 6.



A more detailed explanation on the specified condition:

One by one, the elements in **old_list** will be converted into a string using the **str** function, then it is sliced (as signified by the **[0]** which takes out the first character in the string), then the sliced character is compared to "6". If it is not equal to "6", then the condition is satisfied (as the condition is **!= "6"** which means not equal to "6") and the element will be part of **new_list**.

**Question 20**

In [92]:
z = {1: 'one', 2: 'two', 3: 'three'}

In [93]:
#PART A
if type(z) == dict:
    print("z is a dictionary")
    
print("The length of z is " + str(len(z)))

z is a dictionary
The length of z is 3


PART B

The components before each colon are keys, while the components after each colon are values. I.e. the keys in this dictionary are **1**, **2**, and **3** which are associated to the values **'one'**, **'two'**, and **'three'**, respectively.

In [94]:
#PART C

#To get the value associated to a specific key, type the name of the dictionary followed by
#a square bracket containing the key

z[2]

'two'

In [96]:
#PART D
z.keys?
#z.keys will give us a view of the keys in the dictionary z 
#note it does not create a list containing said keys

z.values?
#z.values will give us a view of the values in the dictionary z
#note it does not create a list containing said values

In [99]:
z.keys()

dict_keys([1, 2, 3])

In [100]:
z.values()

dict_values(['one', 'two', 'three'])

In [101]:
#PART E
list(z.keys())
#This will create a list containing only the keys from the dictionary z

[1, 2, 3]

In [102]:
#PART F
list(z.values())
#This will create a list containing only the values from the dictionary z

['one', 'two', 'three']

In [103]:
#PART G
list(z)
#This will create a list containing only the keys from the dictionary z

[1, 2, 3]

**Question 21**

It took about 180 minutes for me to finish this assignment.